<?php
$generated_array = array(
            'ClassType' => array(
                'class_name' => 'ChurchClassTypeMigration',
                'group_name' => 'ChurchVocabMigrate'
            ),
            'EventType' => array(
                'class_name' => 'ChurchEventTypeMigration',
                'group_name' => 'ChurchVocabMigrate'
            ),
            'AdType' => array(
                'class_name' => 'ChurchAdTypeMigration',
                'group_name' => 'ChurchVocabMigrate'
            ),
            'Department' => array(
                'class_name' => 'ChurchDepartmentMigration',
                'group_name' => 'ChurchVocabMigrate'
            ),
            'Newsletter' => array(
                'class_name' => 'ChurchNewsletterMigration',
                'group_name' => 'ChurchVocabMigrate'
            ),
            'GroupType' => array(
                'class_name' => 'ChurchGroupTypeMigration',
                'group_name' => 'ChurchVocabMigrate'
            ),
            'VolunteerTaskType' => array(
                'class_name' => 'ChurchVolunteerTaskTypeMigration',
                'group_name' => 'ChurchVocabMigrate'
            ),
            'PolicyType' => array(
                'class_name' => 'ChurchPolicyTypeMigration',
                'group_name' => 'ChurchVocabMigrate'
            ),
            'LinkType' => array(
                'class_name' => 'ChurchLinkTypeMigration',
                'group_name' => 'ChurchVocabMigrate'
            ),
            'BlogCategory' => array(
                'class_name' => 'ChurchBlogCategoryMigration',
                'group_name' => 'ChurchVocabMigrate'
            ),
            'GradeAgeRange' => array(
                'class_name' => 'ChurchGradeAgeRangeMigration',
                'group_name' => 'ChurchVocabMigrate'
            ),
            'Tags' => array(
                'class_name' => 'ChurchTagsMigration',
                'group_name' => 'ChurchVocabMigrate'
            ),
);
?>
