<?php
$generated_array = array(
            array(
                'name' => 'Class Type',
                'machine_name' => 'ClassType',
            ),
            array(
                'name' => 'Event Type',
                'machine_name' => 'EventType',
            ),
            array(
                'name' => 'Ad Type',
                'machine_name' => 'AdType',
            ),
            array(
                'name' => 'Department',
                'machine_name' => 'Department',
            ),
            array(
                'name' => 'Newsletter',
                'machine_name' => 'Newsletter',
            ),
            array(
                'name' => 'Group Type',
                'machine_name' => 'GroupType',
            ),
            array(
                'name' => 'Volunteer Task Type',
                'machine_name' => 'VolunteerTaskType',
            ),
            array(
                'name' => 'Policy Type',
                'machine_name' => 'PolicyType',
            ),
            array(
                'name' => 'Link Type',
                'machine_name' => 'LinkType',
            ),
            array(
                'name' => 'Blog Category',
                'machine_name' => 'BlogCategory',
            ),
            array(
                'name' => 'Grade/Age Range',
                'machine_name' => 'GradeAgeRange',
            ),
            array(
                'name' => 'Tags',
                'machine_name' => 'Tags',
            ),
);
?>
